Config = {}

Config.settings = {
    {
        talkAutomatically = false
    }
}

-- Config.speech = {
--     { dialog = "CHAT_PEDTYPE_DIALOG" },
--     { dialog = "CHAT_PEDTYPE_RESPONSE" },
--     { dialog = "CHAT_PEDTYPE_LOCATION" },
--     { dialog = "CONFRONT_UNSEEN" },
--     { dialog = "DEFUSE_RESPONS" },
--     { dialog = "DISMISSIVE_REACT" }
-- }

Config.voice = {
    {
        player_voice = "0732_A_M_M_GUATOWNFOLK_01_HISPANIC_05",
        -- 1014_A_M_M_SDSLUMS_02_BLACK_01
        -- 0723_A_M_M_GUATOWNFOLK_01_HISPANIC_01
        -- 0724_A_M_M_GUATOWNFOLK_01_HISPANIC_02
        -- 0725_A_M_M_GUATOWNFOLK_01_HISPANIC_03
        -- 0732_A_M_M_GUATOWNFOLK_01_HISPANIC_05
        -- 1047_A_M_O_WAPTOWNFOLK_01_NATIVE_02
        -- 0298_A_M_Y_NBXSTREETKIDS_SLUMS_01_WHITE_02
        -- 0297_A_M_Y_NBXSTREETKIDS_SLUMS_01_WHITE_01
        -- 1094_A_M_M_TUMTOWNFOLK_02_BLACK_01
    }
}

Config.speech = {
    [1] =  {["speech"] = "BETTER_REPORT_THIS"},
    [2] =  {["speech"] = "BLOCKED_GGENERIC"},
    [3] =  {["speech"] = "BUMP"},
    [4] =  {["speech"] = "CALM_HORSE"},
    [5] =  {["speech"] = "CHALLENGE_THREATEN"},
    [6] =  {["speech"] = "CHALLENGE_THREATEN_ARMED"},
    [7] =  {["speech"] = "CHALLENGE_THREATEN_SUPPORT"},
    [8] =  {["speech"] = "CHAT_BAD_WEATHER"},
    [9] =  {["speech"] = "CHAT_GOOD_WEATHER"},
    [10] =  {["speech"] = "CHAT_PEDTYPE_DIALOG"},
    [11] =  {["speech"] = "CHAT_PEDTYPE_DIALOG_LOCATION"},
    [12] =  {["speech"] = "CHAT_PEDTYPE_DIALOG_RESPONSE"},
    [13] =  {["speech"] = "CONFRONT_UNSEEN"},
    [14] =  {["speech"] = "COOL_IT"},
    [15] =  {["speech"] = "CUT_THAT_OUT"},
    [16] =  {["speech"] = "DEFUSE_RESPONSE"},
    [17] =  {["speech"] = "DISMISSIVE_REACT"},
    [18] =  {["speech"] = "DISPUTE_INTERVENE_DANGEROUS"},
    [19] =  {["speech"] = "DISPUTE_INTERVENE_HARASSMENT"},
    [20] =  {["speech"] = "DONT_BE_STUPID"},
    [21] =  {["speech"] = "DONT_WANT_TROUBLE"},
    [22] =  {["speech"] = "DRUNK"},
    [23] =  {["speech"] = "EVENT_COMMENT_RESPONSE"},
    [24] =  {["speech"] = "FIGHT"},
    [25] =  {["speech"] = "FIGHT_RESPONSE"},
    [26] =  {["speech"] = "FINAL_WARNING"},
    [27] =  {["speech"] = "GENERIC_ANGRY_REACTION"},
    [28] =  {["speech"] = "GENERIC_ANGRY_SHOUT"},
    [29] =  {["speech"] = "GENERIC_ANTISOCIAL_MALE_EVENT_COMMENT"},
    [30] =  {["speech"] = "GENERIC_CURSE_HIGH"},
    [31] =  {["speech"] = "GENERIC_CURSE_MED"},
    [32] =  {["speech"] = "GENERIC_EXCITING_EVENT_COMMENT"},
    [33] =  {["speech"] = "GENERIC_FRIGHTENED_HIGH"},
    [34] =  {["speech"] = "GENERIC_FRIGHTENED_MED"},
    [35] =  {["speech"] = "GENERIC_GOODBYE"},
    [36] =  {["speech"] = "GENERIC_INSULT_HIGH_NEUTRAL"},
    [37] =  {["speech"] = "GENERIC_INSULT_MED_NEUTRAL"},
    [38] =  {["speech"] = "GENERIC_MOCK"},
    [39] =  {["speech"] = "GENERIC_NO"},
    [40] =  {["speech"] = "GENERIC_SHOCKED_DISBELIEF"},
    [41] =  {["speech"] = "GENERIC_SHOCKED_HIGH"},
    [42] =  {["speech"] = "GENERIC_SHOCKED_MED"},
    [43] =  {["speech"] = "GENERIC_SHOCKING_EVENT_COMMENT"},
    [44] =  {["speech"] = "GENERIC_THANKS"},
    [45] =  {["speech"] = "GENERIC_THANKS_RESPONSE"},
    [46] =  {["speech"] = "GENERIC_THANKS_SHOUTED"},
    [47] =  {["speech"] = "GENERIC_YES"},
    [48] =  {["speech"] = "GET_AWAY_FROM_ME"},
    [49] =  {["speech"] = "GET_LOST"},
    [50] =  {["speech"] = "GET_OUT"},
    [51] =  {["speech"] = "GET_THE_LAW"},
    [52] =  {["speech"] = "GIDDY_UP"},
    [53] =  {["speech"] = "GIDDY_UP_ESCALATED"},
    [54] =  {["speech"] = "GOING_BADLY"},
    [55] =  {["speech"] = "GOING_WELL"},
    [56] =  {["speech"] = "GOODBYE_PEDTYPE_CUSTOM"},
    [57] =  {["speech"] = "GREET_GENERAL_FAMILIAR"},
    [58] =  {["speech"] = "GREET_GENERAL_STRANGER"},
    [59] =  {["speech"] = "GREET_PED_CAPTURED_BOUNTY"},
    [60] =  {["speech"] = "GREET_PLAYER_CAPTURED_BOUNTY"},
    [61] =  {["speech"] = "GREET_PLAYER_MASK"},
    [62] =  {["speech"] = "GREET_REJECT"},
    [63] =  {["speech"] = "GREET_SICK"},
    [64] =  {["speech"] = "GUN"},
    [65] =  {["speech"] = "GUN_AVOID"},
    [66] =  {["speech"] = "HAND_OVER_MONEY"},
    [67] =  {["speech"] = "HOWS_IT_GOING"},
    [68] =  {["speech"] = "IGNORING_YOU"},
    [69] =  {["speech"] = "INSULT_RESPONSE"},
    [70] =  {["speech"] = "INTIMIDATED_GEN"},
    [71] =  {["speech"] = "INTIMIDATED_ROB"},
    [72] =  {["speech"] = "INTIMIDATED_WITNESS"},
    [73] =  {["speech"] = "LAW_HAIL"},
    [74] =  {["speech"] = "LAW_TATTLE_ASSAULT"},
    [75] =  {["speech"] = "LAW_TATTLE_FEMALE"},
    [76] =  {["speech"] = "LAW_TATTLE_MALE"},
    [77] =  {["speech"] = "LAW_TATTLE_MURDER"},
    [78] =  {["speech"] = "LAW_TATTLE_NEUTRAL"},
    [79] =  {["speech"] = "LAW_TATTLE_THEFT"},
    [80] =  {["speech"] = "LEAVE_NOW"},
    [81] =  {["speech"] = "MELEE"},
    [82] =  {["speech"] = "MELEE_BRING_IT_ON"},
    [83] =  {["speech"] = "MELEE_TAKE_THAT"},
    [84] =  {["speech"] = "MELEE_THAT_ALL_YOU_GOT"},
    [85] =  {["speech"] = "NICE_HORSE"},
    [86] =  {["speech"] = "NICE_KILL_GENERAL"},
    [87] =  {["speech"] = "NICE_KILL_LOADED"},
    [88] =  {["speech"] = "NICE_WAGON"},
    [89] =  {["speech"] = "NO_IDEA"},
    [90] =  {["speech"] = "OPENS_FIRE"},
    [91] =  {["speech"] = "PANIC_COMMUNICATE"},
    [92] =  {["speech"] = "PANIC_HELP"},
    [93] =  {["speech"] = "PEDTYPE_WON_DISPUTE"},
    [94] =  {["speech"] = "PEDTYPE_WON_FIGHT"},
    [95] =  {["speech"] = "PLAYER_ACTING_WEIRD"},
    [96] =  {["speech"] = "PLAYER_AIMING_NOBODY"},
    [97] =  {["speech"] = "PLAYER_CARRY_DEAD_PED"},
    [98] =  {["speech"] = "PLAYER_FOLLOWING"},
    [99] =  {["speech"] = "PLAYER_INTERACT_CHAT"},
    [100] =  {["speech"] = "PLAYER_INTERACT_CHAT_BOUNTY"},
    [101] =  {["speech"] = "PLAYER_INTERACT_CHAT_HUNTING"},
    [102] =  {["speech"] = "PLAYER_INTERACT_CHAT_WANTED"},
    [103] =  {["speech"] = "PLAYER_INTERACT_NEG_REPLY"},
    [104] =  {["speech"] = "PLAYER_INTERACT_PULL_OVER"},
    [105] =  {["speech"] = "PLAYER_INTERACT_PULL_OVER_EXTREME"},
    [106] =  {["speech"] = "PLAYER_INTERACT_PULL_OVER_SHOUTED"},
    [107] =  {["speech"] = "PLAYER_INTERACT_PULL_OVER_SHOUTED_EXTREME"},
    [108] =  {["speech"] = "PLAYER_INTERACT_UNFRIENDLY_TAIL_OFF"},
    [109] =  {["speech"] = "PLAYER_LASSO_SWINGING"},
    [110] =  {["speech"] = "PLAYER_LOITERING"},
    [111] =  {["speech"] = "PLAYER_LOOKING_WEIRD"},
    [112] =  {["speech"] = "PLAYER_STARING"},
    [113] =  {["speech"] = "PLAYER_WEAPON_EQUIPPED"},
    [114] =  {["speech"] = "PLEAD"},
    [115] =  {["speech"] = "PLEAD_HOGTIED"},
    [116] =  {["speech"] = "POST_THEFT"},
    [117] =  {["speech"] = "RELIEVED_REACT"},
    [118] =  {["speech"] = "RESPONSE_GGENERIC"},
    [119] =  {["speech"] = "RESPONSE_GOOD_WEATHER"},
    [120] =  {["speech"] = "RT_BOUNTY_WARNING"},
    [121] =  {["speech"] = "RT_FRIENDLY_STAY_ALL_DAY_LONG"},
    [122] =  {["speech"] = "RT_GGENERIC_COMMENT"},
    [123] =  {["speech"] = "RT_GET_OUT"},
    [124] =  {["speech"] = "RT_HAND_OVER_ITEM"},
    [125] =  {["speech"] = "RT_HAND_OVER_MONEY"},
    [126] =  {["speech"] = "RT_HEADS_UP_FRIENDLY_CAMP"},
    [127] =  {["speech"] = "RT_HEADS_UP_NIGHT_CAMP"},
    [128] =  {["speech"] = "RT_HEADS_UP_NIGHT_ROAD"},
    [129] =  {["speech"] = "RT_HEADS_UP_WARY_CAMP"},
    [130] =  {["speech"] = "RT_HEADS_UP_WARY_ROAD"},
    [131] =  {["speech"] = "RT_HELP_YOURSELF"},
    [132] =  {["speech"] = "RT_INTIMIDATED_AGAIN_ROB_SUPPLY"},
    [133] =  {["speech"] = "RT_INTIMIDATED_AGAIN_ROB_THREATEN"},
    [134] =  {["speech"] = "RT_INTIMIDATED_ROB_COACH"},
    [135] =  {["speech"] = "RT_INTIMIDATED_ROB_DEFUSE"},
    [136] =  {["speech"] = "RT_INTIMIDATED_ROB_NOT_INTIMIDATED"},
    [137] =  {["speech"] = "RT_INTIMIDATED_ROB_THREATEN"},
    [138] =  {["speech"] = "RT_NO_TIME_FOR_THIS"},
    [139] =  {["speech"] = "RT_ORDER_DISMOUNT_NEG"},
    [140] =  {["speech"] = "RT_ORDER_DISMOUNT_POS"},
    [141] =  {["speech"] = "RT_POST_THEFT"},
    [142] =  {["speech"] = "RT_WE_DONE_HERE"},
    [143] =  {["speech"] = "SCARED_COMMUNICATE"},
    [144] =  {["speech"] = "SCARED_HELP"},
    [145] =  {["speech"] = "SEARCHING_FOUND_NOTHING"},
    [146] =  {["speech"] = "SHAME_ON_YOU"},
    [147] =  {["speech"] = "SHERIFF_HAIL"},
    [148] =  {["speech"] = "SICK_BASTARD"},
    [149] =  {["speech"] = "SORRY_TO_HEAR_THAT"},
    [150] =  {["speech"] = "STAGECOACH_HOP_ON_INVITE"},
    [151] =  {["speech"] = "STEAL_BACK"},
    [152] =  {["speech"] = "STOP_THAT"},
    [153] =  {["speech"] = "TAUNT_GEN_NEUTRAL"},
    [154] =  {["speech"] = "THREATEN_UNSEEN"},
    [155] =  {["speech"] = "TIME_TO_GO"},
    [156] =  {["speech"] = "VICTIMIZED_REACT"},
    [157] =  {["speech"] = "WARNED_ALREADY"},
    [158] =  {["speech"] = "WAS_THIS_YOU"},
    [159] =  {["speech"] = "WHATS_GOING_ON"},
    [160] =  {["speech"] = "WHATS_YOUR_PROBLEM"},
    [161] =  {["speech"] = "WHAT_IS_THAT"},
    [162] =  {["speech"] = "WHAT_WAS_THAT"},
    [163] =  {["speech"] = "WHOA"},
    [164] =  {["speech"] = "WHOA_ESCALATED"},
    [165] =  {["speech"] = "WON_DISPUTE"},
    [166] =  {["speech"] = "WON_FIGHT"},
    [167] =  {["speech"] = "WON_DISPUTE"},
    [168] =  {["speech"] = "WRONGED_RECENTLY"},
    [169] =  {["speech"] = "YOU_SHOULDNT_BE_HERE"},
    [170] =  {["speech"] = "INTIMIDATED_AGAIN_GEN"},
    [171] =  {["speech"] = "BUMP_SICK"},
    [172] =  {["speech"] = "CALL_FOR_SUPPORT_FAR"},
    [173] =  {["speech"] = "CALL_FOR_SUPPORT_FAR_RESPONSE"},
    [174] =  {["speech"] = "BATTLE_CRY"},
    [175] =  {["speech"] = "COMBAT_FLEE"},
    [176] =  {["speech"] = "CHAT_FLATTER_01"},
    [177] =  {["speech"] = "CHAT_RESPONSE_A_01"},
    [178] =  {["speech"] = "DONT_ANNOY_ME_01"},
    [179] =  {["speech"] = "COOL_IT_01"},
    [180] =  {["speech"] = "DRUNK_01"},
    [181] =  {["speech"] = "GENERIC_ANGRY_SHOUT_01"},
    [182] =  {["speech"] = "GENERIC_BUY_01"},
    [183] =  {["speech"] = "GENERIC_CHEER_ON_01"},
    [184] =  {["speech"] = "GENERIC_CURSE_HIGH_01"},
    [185] =  {["speech"] = "GENERIC_CURSE_MED_02"},
    [186] =  {["speech"] = "GENERIC_FRIGHTENED_HIGH_03"},
    [187] =  {["speech"] = "GENERIC_NO_01"},
    [188] =  {["speech"] = "GENERIC_MOCK_01"},
    [189] =  {["speech"] = "GENERIC_SHOCKED_MED_02"},
    [190] =  {["speech"] = "GET_THE_LAW_01"}
}